name: archive_app

description: "A new Flutter project."

publish_to: 'none' 

version: 1.7.8+0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl:  ^0.19.0
  metadata_fetch: ^0.4.2
  shared_preferences: ^2.2.2
  url_launcher: ^6.1.10
  cupertino_icons: ^1.0.8
  http: ^1.3.0
  html: ^0.15.0
  palette_generator: ^0.3.3
  flutter_speed_dial: ^7.0.0
  #firebase_core: ^4.0.0
  #firebase_auth: ^6.0.1
  #cloud_firestore: ^6.0.0
  fl_chart: ^0.65.0
  image_picker: ^1.0.0
  flutter_riverpod: ^2.6.1
  google_mobile_ads: ^6.0.0
  path_provider: ^2.1.1
  path: ^1.9.0
  purchases_flutter: ^9.2.1
  app_tracking_transparency: ^2.0.6+1
  #webview_flutter: ^4.13.0
  #webview_flutter_android: ^4.13.0
  #webview_flutter_wkwebview: ^4.13.0
  flutter_inappwebview: ^6.1.5
  in_app_review: ^2.0.11

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  generate: true

  assets:
    - assets/icons/critical.png
    - assets/icons/normal.png
    - assets/icons/maniac.png
    - assets/icons/critical_gray.png
    - assets/icons/normal_gray.png
    - assets/icons/maniac_gray.png

  fonts:
    - family: NotoSerifJP
      fonts:
        - asset: assets/fonts/NotoSerifJP-VariableFont_wght.ttf

  uses-material-design: true
